<ProgressBar>:
    canvas:
        Clear
        Color:
            rgba: (0.26, 0.26, 0.26, 1)
        Rectangle:
            pos: self.x, self.center_y - 0.5 * dp(100)  # Adjust dp(20) to change thickness
            size: self.width, dp(100)  # Adjust dp(20) to change thickness

        Color:
            rgba: (0.4, 0.4, 0.4, 1)
        Rectangle:
            pos: self.x, self.center_y - 0.5 * dp(100)  # Adjust dp(20) to change thickness
            size: self.width * self.value_normalized, dp(100)  # Adjust dp(20) to change thickness